version: '3'
services:
  server-flask:
    build:
      context: ./backend/
    ports:
      - 5000:5000
    command: >
     sh -c "python3 -m flask --app app run --host=0.0.0.0 --port=5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    depends_on:
      - postgres
  client-react:
    build:
      context: ./frontend/
    stdin_open: true
    ports:
      - 30:3000
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:14-alpine3.17
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
volumes:
  pgdata:

