"""empty message

Revision ID: 63029087fd84
Revises: de813851ad0f
Create Date: 2023-11-25 14:56:23.759768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63029087fd84'
down_revision = 'de813851ad0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
